version: '3'
services:
  database:
    image: mysql:5.7
    ports:
      - "3309:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: resource
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
    container_name: resource-db-1
